### PR TITLE
Mobile-esq flip switches

### PR DESCRIPTION
**Pull request by hobnob**
Adds flip switched (On or Off) to amazium forms, a little like the JQuery flip switches:
http://demos.jquerymobile.com/1.2.0/docs/forms/switch/

Example here:
http://codepen.io/hobnob/pen/YyOPbV

### CODE REVIEW

**Comment by catchamonkey** [comment]
Not bad! Except that's really weird for radios as you can't click to go back to off.

Shouldn't do this for Radios I don't think.

@MikeBallan has a similar thing, but with styling ;)

radionono

**Comment by catchamonkey** [comment]
@MikeBallan can you add a PR for the version you worked on please?
Compare notes...

**Comment by hobnob** [comment]
Yeah @MikeBallan mentioned he'd done something similar

The radio buttons were actually last minute additions. I had no need for it, but thought there might be a use case for people in either-or scenarios.

Will remove them though, no biggy :-)

**Comment by catchamonkey** [comment]
Yeah, not much code, but I think as it doesn't make sense from a UX perspective, it's not good to add support for it built-in.

**Comment by hobnob** [comment]
:+1: Agreed and removed

**Comment by catchamonkey** [comment]
Cool, just wait for @MikeBallan to have a look and compare and tweak styling maybe.

**Comment by hobnob** [comment]
:+1:

**Comment by catchamonkey** [comment]
Change incoming, please hold. 📞 

Thanks!

**Pull request closed without merging**
