### PR TITLE
[Forms] Updates height of inputs and converts over the using SCSS

### PR DESCRIPTION
**Pull request by MikeBallan**
- Updates colors to use variables
- Buttons now have more color options
- Button states are better styled
- Changes the checkboxes background color to use the info color to be the same as radios
- Forms.scss now using mainly SCSS over plain CSS

### CODE REVIEW

**Comment by catchamonkey** [comment]
Cool, I'll get autoprefixer sorted on this repo 👍

**Comment by MikeBallan** [comment]
Sweet

**Comment by catchamonkey** [comment]
if you're happy with this, then I will do a new release @MikeBallan ?

**Comment by Solinx** [comment]
@MikeBallan @catchamonkey Good to go?

**Comment by catchamonkey** [comment]
LGTM, @MikeBallan ?

**Comment by MikeBallan** [comment]
Yup all good..!

**Pull request merged**
