### PR TITLE
V5 [Tables on mobile] Fixes styling for mobile tables

### PR DESCRIPTION
**Pull request by MikeBallan**
Adds styling by way of adding table-mobile class to a table

image

### CODE REVIEW

**Comment by MikeBallan** [comment]
@catchamonkey You want me to merge this..?

**Comment by catchamonkey** [comment]
> You want me to merge this..?

You want a new release?

**Comment by MikeBallan** [comment]
Yes please..!

**Comment by MikeBallan** [comment]
Then i think V5 is all good for stable release..!

**Comment by catchamonkey** [comment]
> Then i think V5 is all good for stable release..!

will release one more pre release so site can be updated, then can go stable, launch site, and blog post in one.

**Pull request merged**
