### PR TITLE
Buttons & Typography updates

### PR DESCRIPTION
**Pull request by MikeBallan**
* Moves the styling for the buttons to the form.css file
* Updates the Pre & code styling
* Form example page now has the loading states for buttons in them
* Font sizes changed for headings and paragrahs

### CODE REVIEW

**Comment by catchamonkey** [comment]
Any screenshot of before and after?

**Comment by MikeBallan** [comment]
screencapture-file-users-mikeballan-sites-amazium-example-html

**Comment by MikeBallan** [comment]
screencapture-file-users-mikeballan-sites-amazium-forms-html

**Comment by MikeBallan** [comment]
The screenshots above show the newer version of the example pages

**Pull request merged**
